/**
 * Starts a local embedded Postgres for HiddenSpots, writes .env.local, pushes schema.
 * Keep this process running — Next.js connects to it.
 *
 * Usage: node scripts/local-db.mjs
 */
import EmbeddedPostgres from "embedded-postgres";
import { spawn } from "node:child_process";
import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";

const PORT = 5433;
const USER = "postgres";
const PASSWORD = "hiddenspots";
const DB_NAME = "hiddenspots";
const DATA_DIR = join(process.cwd(), ".data", "pg");

const DATABASE_URL = `postgresql://${USER}:${PASSWORD}@127.0.0.1:${PORT}/${DB_NAME}?schema=public`;
const AUTH_SECRET = randomBytes(32).toString("base64url");

async function main() {
  mkdirSync(DATA_DIR, { recursive: true });

  const pg = new EmbeddedPostgres({
    databaseDir: DATA_DIR,
    user: USER,
    password: PASSWORD,
    port: PORT,
    persistent: true,
    initdbFlags: ["--locale=C", "--encoding=UTF8"],
  });

  console.log("[local-db] Initialising Postgres cluster…");
  if (!existsSync(join(DATA_DIR, "PG_VERSION"))) {
    await pg.initialise();
  } else {
    console.log("[local-db] Cluster already exists, reusing.");
  }

  console.log(`[local-db] Starting on port ${PORT}…`);
  await pg.start();

  try {
    await pg.createDatabase(DB_NAME);
    console.log(`[local-db] Created database "${DB_NAME}"`);
  } catch {
    console.log(`[local-db] Database "${DB_NAME}" already exists`);
  }

  const env = `# Local HiddenSpots — generated by scripts/local-db.mjs
# Do not commit. Embedded Postgres on port ${PORT}.

DATABASE_URL="${DATABASE_URL}"
DIRECT_URL="${DATABASE_URL}"

AUTH_SECRET="${AUTH_SECRET}"
NEXTAUTH_URL="http://localhost:3000"
AUTH_URL="http://localhost:3000"

# OAuth — optional for first run (email/password signup works)
AUTH_GOOGLE_ID=""
AUTH_GOOGLE_SECRET=""
AUTH_GITHUB_ID=""
AUTH_GITHUB_SECRET=""

# Maps — Leaflet/OSM works with no keys; Mapbox/Google optional
NEXT_PUBLIC_MAPBOX_TOKEN=""
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=""

BLOB_READ_WRITE_TOKEN=""
SERWIST_SUPPRESS_TURBOPACK_WARNING=1
`;

  writeFileSync(join(process.cwd(), ".env.local"), env, "utf8");
  console.log("[local-db] Wrote .env.local");

  console.log("[local-db] Pushing Prisma schema…");
  await run("npx", ["prisma", "db", "push", "--skip-generate"], {
    DATABASE_URL,
    DIRECT_URL: DATABASE_URL,
  });

  console.log("[local-db] Starting Next.js…");
  const next = spawn("npx", ["next", "dev", "--port", "3000"], {
    stdio: "inherit",
    shell: true,
    env: {
      ...process.env,
      DATABASE_URL,
      DIRECT_URL: DATABASE_URL,
      AUTH_SECRET,
      NEXTAUTH_URL: "http://localhost:3000",
      AUTH_URL: "http://localhost:3000",
      SERWIST_SUPPRESS_TURBOPACK_WARNING: "1",
    },
  });

  const shutdown = async () => {
    console.log("\n[local-db] Shutting down…");
    next.kill("SIGTERM");
    try {
      await pg.stop();
    } catch {
      /* ignore */
    }
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  next.on("exit", async (code) => {
    try {
      await pg.stop();
    } catch {
      /* ignore */
    }
    process.exit(code ?? 0);
  });
}

function run(cmd, args, extraEnv = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, {
      stdio: "inherit",
      shell: true,
      env: { ...process.env, ...extraEnv },
    });
    child.on("exit", (code) => (code === 0 ? resolve() : reject(new Error(`${cmd} exited ${code}`))));
  });
}

main().catch((e) => {
  console.error("[local-db] Failed:", e);
  process.exit(1);
});
